### ISSUE TITLE
Array state

### ISSUE THREAD

**Issue by roman-koshchei** [vanjs-org/van#113]
I have such function to render to-do list. But it doesn't re-render after click on button. 
As I understand, it's because I use `.map` with `.val`. So state doesn't track changes in there.
How to use `.map` with array state?

```ts
function todo() {
  const todos = van.state(["AAA", "BBB", "CCC"])

  return el.ul(
    todos.val.map((x) =>
      el.li(
        el.button(
          {
            onclick: () => {
              todos.val = todos.val.filter((value) => value != x)
            },
          },
          x
        )
      )
    )
  )
}
```

**Comment by Tao-VanJS** [comment]
To make your app reactive to state changes, the state access needs to be wrapped inside a binding function, see [State-derived child nodes](https://vanjs.org/tutorial#state-derived-child). The binding function needs to return a DOM node (an array of DOM nodes is not accepted), thus for your app, we can wrap it around a `<div>` element.

Your code can be modified to the following to work:

```js
function todo() {
  const todos = van.state(["AAA", "BBB", "CCC"])

  return el.ul(
    () => el.div(todos.val.map((x) =>
      el.li(
        el.button(
          {
            onclick: () => {
              todos.val = todos.val.filter((value) => value != x)
            },
          },
          x
        )
      )
    ))
  )
}
```

You can preview it here: https://jsfiddle.net/0xbcdm5q/11/.

**Comment by roman-koshchei** [comment]
Is it okay to always use a function even if it doesn't have DOM derived state?
So always such syntax:
```ts
function counter() {
  const state = van.state(0)
  return () => el.button({ onclick: () => (state.val += 1) }, state)
}
```

**Comment by Tao-VanJS** [comment]
Yes. Both tag functions and `van.add` accept binding functions. But returning functions doesn't make much difference compared to returning the elements directly, as the resulting DOM elements aren't bound to any states anyway.

**Comment by roman-koshchei** [comment]
Just if always return functions, then it will always respond to state changes in the right way (as with arrays)

**Comment by Tao-VanJS** [comment]
Closing the issue as it was resolved.
