### ISSUE TITLE
Question: updating attributes (eg. 'className') without re-generating whole sub-DOM

### ISSUE THREAD

**Issue by metaleap** [vanjs-org/van#116]
Considering the case of a tabbed-container component with say 3 tabs, only any 1 of them to be ever visible, and a van state var named `activeIdx`.

The requirement: when switching active-tab, the other tabs should just become hidden of course — but remain in the DOM in their current UI state (like scroll position in tab itself or some textarea). No re-generating DOM on hiding or showing, by adding/removing a custom CSS class (eg. 'active') via script on tab switch.

Right now, I'm doing like `document.getElement('tab_' + i).classList.add/remove('active')` in the van.derive handler for `activeIdx`. And it works.

My question is whether there are any hidden gotchas with this approach in a VanJS context or whether this is unproblematic  =)  I read somewhere a warning about custom DOM manipulations in your docs or threads some days ago but can't find it again right now.

**Comment by Tao-VanJS** [comment]
If you bind a state only to a property, not to the whole DOM node, the DOM node won't be regenerated when the state is updated. We have an example here: https://vanjs.org/tutorial#state-typed-prop to illustrate this.

Let me know if this can resolve your issue.

**Comment by metaleap** [comment]
Brilliant, that's indeed a better way than all that element-IDs noise! Sorry for making an "Issue" for a mere question, could have been a "Discussions" post, but I'm not yet used to that new Github feature  =)
