### ISSUE TITLE
Remember local state

### ISSUE THREAD

**Issue by dkirchhof** [vanjs-org/van#121]
Hey,
I just wanted to try out VanJS by implementing a todo app.
While there are two examples - a procedural and a reactive one - I prefer the latter. 

So here is a small snippet of my app:

```js
const App = () => {
  const todos = van.state([{ task: "test", done: false }]);

  const onAddTodoClick = () => {
    todos.val = [...todos.val, { task: "new task", done: false }];
  };

  return van.tags.div(
    van.tags.button({ onClick: onAddTodoClick }, "+"),
    () => van.tags.ul(todos.val.map(todo => TodoItem({ todo })))
  );
};

const TodoItem = props => {
  const edit = van.state(false);

  const onEditClick = e => {
    e.stopPropagation();

    edit.val = true;
  };

  return () => van.tags.li(
    edit.val ? "edit" : props.todo.task,
    van.tags.button({ onClick: onEditClick }, "edit"),
  ); 
};
```
(this code is out of my head - can't test it right now)

Unfortunately if I click on an item to edit it and add a new item to the list, the list will be rerendered completely. So all items will be in the "normal" state again.

Asked in [this thread](https://github.com/vanjs-org/van/discussions/118), there is a procedural solution, but as a longtime react developer, I would like to know, if there is also a functional solution without saving the todo item state also in the app state.

**Comment by Tao-VanJS** [comment]
For your specific requirement, I think you can preserve whether an item is in an "edit" state or a "normal" state in a VanJS state object (something created by `van.state(...)`). In this way, whenever you add a new item to the list and the entire todo items need to be re-rendered, it will be re-rendered according to what are stored in all state objects.

**Comment by Tao-VanJS** [comment]
If you don't want to preserve the todo item states in the app state, you can also choose to preserve the value in `data-...` attributes of the relevant DOM elements. And whenever re-rendering happens, you can query the attribute values and re-render the todo list based on them.

**Comment by dkirchhof** [comment]
I don't get your second approach. If I store the edit state in a data attribute (of the list item dom), it will get lost after rerendering the list, because each element will be deleted and new elements will be created. Am I wrong?

**Comment by Tao-VanJS** [comment]
You can leverage [stateful binding](https://vanjs.org/tutorial#stateful-binding), where the binding function can take one parameter which is the DOM element that you want to change or re-render. From this input DOM element you can get values from `data-...` attributes. You can see this technique being used in our [hydration example](https://vanjs.org/ssr#hydration).

**Comment by dkirchhof** [comment]
Okay, I could save the state in a data-state variable in each "li". When I rerender the list, I could restore the state from the data attributes. Right.
But I would like to keep the behavior as generic as possible. So if I have another list with probably more than one state It gets complicated. And if the list items contain further components with local states this restoring process has to be recursive as well...

Maybe I will build a helper component for lists. But I'm not really happy with this idea.
Thanks anyway

**Comment by Tao-VanJS** [comment]
I feel that https://github.com/vanjs-org/van/issues/121#issuecomment-1724476849 might be the better approach (compared to the `data-...` attributes in the DOM elements). It would be always a good practice to keep the UI states in sync with state objects in VanJS. This helps the extensibility of your app. For instance, if you want to serialize your app states into some storage, having UI states captured in the state objects definitely helps.

**Comment by dkirchhof** [comment]
Sure. I can also add the edit state to the array of todo items in the app state. Since the todo app is only a simple example, I don't know, if it will fit in more complex apps as well. I will see :)
