### ISSUE TITLE
Van JSX package is not published to npm registry

### ISSUE THREAD

**Issue by phelma** [vanjs-org/van#134]
[vanjs-jsx](https://github.com/vanjs-org/van/tree/main/addons/van_jsx) Has not been published to the npm registry, so the [steps in the readme ](https://github.com/vanjs-org/van/blob/48de9b20ca9556a488ff320c3df171014a0e3722/addons/van_jsx/README.md?plain=1#L16) do not work

**Comment by Tao-VanJS** [comment]
@cqh963852, can you take a look at this issue?

**Comment by cqh963852** [comment]
I have publish @idealjs/van-jsx.

But I think it is more appropriate to maintain it in vanjs repo and publish it to `vanjs-jsx`.

Can you publish vanjs-jsx to npm registry?

**Comment by Tao-VanJS** [comment]
Thanks @cqh963852 for the quick response!

I just published the NPM package: https://www.npmjs.com/package/vanjs-jsx.

@phelma, let me know if it solves the problem.

**Comment by phelma** [comment]
amazing, thank you!
