### ISSUE TITLE
"state functions" dependencies

### ISSUE THREAD

**Issue by sKopheK** [vanjs-org/van#137]
hi, back in v0.x `van.bind()` asked for dependency array, since v1.x it's handled automatically, which is convenient, but not always what you want. it might not be the best practice, but sometimes you want to trigger the "state function" when some state you're not reffering in the function changes.

example: graph nodes w/ linked siblings. i want to output list of selected node's siblings. when i change change time, selected node's siblings might dis/appear, so i want to update list upon this change.

i don't want to create new array of selected nodes just because of this case and only other thing i can think of is referring the value and not using it, but does not feel "right"  :) and also might stop working in future as it's kinda hacky way

```
() => {
    state2.val;  <-- is not used
    return state1.val;
}

```

**Comment by Tao-VanJS** [comment]
For the rare occasions where you want a state derivation to be triggered on a state that is not being used, the way you described is recommended.

We're using this technique occasionally in some sample apps of VanJS. For instance, in the [`AutoComplete` app](https://vanjs.org/demo#auto-complete), you can see the code like this:

```js
// Resetting selectedIndex to 0 whenever candidates change
const selectedIndex = van.derive(() => (candidates.val, 0))
```
