### ISSUE TITLE
TypeScript error when using State inside JSX element

### ISSUE THREAD

**Issue by yahia-berashish** [vanjs-org/van#138]
When using van_jsx, I noticed that using a state as an element child will cause a TypeScript error:
**Type 'State<number>' is not assignable to type 'ComponentChild'.**

The issue was solved very simply by adding the Sate type imported from `vanjs-core` to the ComponentChild type in `type.d.ts`: 
Before: 
export type ComponentChild =
  | FunctionChild<any>
  | Element
  | string
  | number
  | bigint
  | boolean
  | null
  | undefined;

After - this solves the problem:
export type ComponentChild =
  | FunctionChild<any>
  | Element
  | string
  | number
  | bigint
  | boolean
  | null
  | undefined 
  | State

**Comment by Tao-VanJS** [comment]
@cqh963852, do you want to take a look at this issue?

**Comment by cqh963852** [comment]
@yahia-berashish I think this idea is right. Can you open a pull request according to your idea?

**Comment by cqh963852** [comment]
Another type problem is `lazy` function, this is a magic type modification.

We should remove this function.

**Comment by yahia-berashish** [comment]
> Another type problem is `lazy` function, this is a magic type modification.
> 
> https://github.com/vanjs-org/van/blob/48de9b20ca9556a488ff320c3df171014a0e3722/addons/van_jsx/src/index.js#L3-L5
> 
> https://github.com/vanjs-org/van/blob/48de9b20ca9556a488ff320c3df171014a0e3722/addons/van_jsx/src/index.d.ts#L3
> 
> We should remove this function.

what is exactly the issue with `lazy`?

**Comment by cqh963852** [comment]
The correct declaration of lazy function should be ` export declare const lazy: <T>(f: () => T) => ()=>T;`

And the lazy function does nothing and has no actual value

**Comment by yahia-berashish** [comment]
So, should we remove it from the code or change the type declaration?
It can be used as a placeholder for a later update maybe.

**Comment by cqh963852** [comment]
> So, should we remove it from the code or change the type declaration? It can be used as a placeholder for a later update maybe.

I think it's better to just remove this function from code.

Because not many people are using it yet, it is more appropriate to remove it now. 

If removed later, there will be forward compatibility issues.

**Comment by yahia-berashish** [comment]
Well, forget about that, I've found something else.
The ComponentChild and FunctionChild types don't support the ChildDom type, and this is really weird behavior, the types of the core library and van_jsx have to be compatible.
I've checked the code, and adding ChildDom to ComponentChild and FunctionChild works just fine.
Will include it in the next PR.

**Comment by yahia-berashish** [comment]
> Well, forget about that, I've found something else. The ComponentChild and FunctionChild types don't support the ChildDom type, and this is really weird behavior, the types of the core library and van_jsx have to be compatible. I've checked the code, and adding ChildDom to ComponentChild and FunctionChild works just fine. Will include it in the next PR.

this also actually solves the first issue, since the ChildDom type includes the State type.

**Comment by yahia-berashish** [comment]
All done 
Waiting to merge...

**Comment by Tao-VanJS** [comment]
Hi @yahia-berashish,

I am not seeing your latest commit in #139.

**Comment by yahia-berashish** [comment]
I haven't committed yet, I'm a bit busy at the moment, but I should be able to address to issue and add the commit to the PR after a few hours.

**Comment by yahia-berashish** [comment]
The commit is pushed, the PR must be ready for merge now @Tao-VanJS
