### ISSUE TITLE
Can't listen to events which are not available as on... properties (for example focusout)

### ISSUE THREAD

**Issue by MrVoltz** [vanjs-org/van#146]
Some events don't have their attribute counterparts, one such example is [focusout](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event). Maybe it would be better if VanJS just bound all events handlers (properties starting with `on` whose value is a function) using `addEventListener` instead of relying on the DOM properties. 

This would also make event names case insensitive (I like to use camelCase for event names).

Jsfiddle: https://jsfiddle.net/uqbt36mz/4/

**Comment by Tao-VanJS** [comment]
Does `onblur` event handler work for your use case?

It's really weird that `focusout` and `focusin` events don't have the corresponding properties for event handlers. Not sure why the HTML standard is designed this way. I will keep this improvement idea in mind.

btw: right now I don't recommend to use camelCase for `on...` event handlers, as it is currently reserved for [a special purpose](https://vanjs.org/ssr#on-properties).

**Comment by Tao-VanJS** [comment]
The support for custom event handers was added in 1.2.8: https://github.com/vanjs-org/van/discussions/246.

**Comment by Tao-VanJS** [comment]
@all-contributors please add @MrVoltz for bug
