### ISSUE TITLE
Add a disclaimer to explain the difference between VanJS and "Vanilla JavaScript"

### ISSUE THREAD

**Issue by steren** [vanjs-org/van#18]
"vanilla JS" is a term used to designate using JS without any framework.

Naming a framework "Vanilla JS" (even if abbreviated) is confusing. 

This HackerNews thread discusses the problem: https://news.ycombinator.com/item?id=36068142

**Comment by zamadatix** [comment]
See https://github.com/vanjs-org/van/issues/9

**Comment by steren** [comment]
At minimum, please update the README to not mention "vanilla"

**Comment by Tao-VanJS** [comment]
Thank you for raising this issue again! I will explore options and find a suitable way to get it resolved.
