### ISSUE TITLE
How to get access to DOM elements (like refs in React)

### ISSUE THREAD

**Issue by kwameopareasiedu** [vanjs-org/van#204]
First of all, this is a really great project. Now trying it hands-on and I've run into an issue **How  I need to access the DOM element**?

Here's a minimal example:

`index.ts`
```
import "./styles/global.css";
import van from "vanjs-core";
import App from "@/app.ts";

const root = document.querySelector<HTMLDivElement>("#app");

if (root) van.add(root, App());
```

`app.ts`
```
import van from "vanjs-core";

const { canvas } = van.tags;

export default function App() {
  van.derive(() => {
    const c = document.querySelector("#container") as Element;
    console.log(c); // always null
  });

  return canvas({ id: "container", class: "text-xl" });
}
```

In `App` I would like to get a reference to the returned div. The current approach with `document.querySelector` always returns `null`.

**Comment by Tao-VanJS** [comment]
The function argument of `van.derive` is invoked when `van.derive` is being called, or whenever the `val` property a state object referred by the binding function changes.

In your example, the binding function here:

```ts
  van.derive(() => {
    const c = document.querySelector("#container") as Element;
    console.log(c); // always null
  });
```

doesn't refer to any states, thus it will only be invoked when `van.derive` is called. At that time, the element hasn't been attached to the document tree, which is the reason why `document.querySelector("#container")` returns `null`.

To get the element, you can consider to organize the code like that:

```ts
export default function App() {
  const c = canvas({ id: "container", class: "text-xl" });
  console.log(c); // The element `c` will be printed

  return c;
}
```

Hope it helps :-)

**Comment by kwameopareasiedu** [comment]
Ohk. That makes sense. I just tried it and got the desired results.

Awesome work btw. Really looking forward to the future of the project.
