### ISSUE TITLE
VanJS Router?

### ISSUE THREAD

**Issue by kwameopareasiedu** [vanjs-org/van#205]
I wanted to know whether VanJS has any plans for a router?

If not, which vanilla js router do you recommend to use which can preserve state.

**Comment by b-rad-c** [comment]
Hey there, you try out the [Van Cone](KHL6ToaGrRKkKRhtxWtY9P) extension I wrote!

**Comment by kwameopareasiedu** [comment]
@b-rad-c Nice work on van-cone. However, I wanted to also take a shot at it and rolled out a new routing library for VanJS.

@Tao-VanJS @b-rad-c Check out `VanJS-Routing` https://www.npmjs.com/package/vanjs-routing

**Comment by Tao-VanJS** [comment]
@kwameopareasiedu, awesome! I added "VanJS Routing" into the [Community Add-ons](https://vanjs.org/#community-add-ons) section of VanJS. Thank you so much for your contribution!

**Comment by Tao-VanJS** [comment]
@all-contributors please add @kwameopareasiedu for plugin
