### ISSUE TITLE
Reactivity is broken when the context is quickly switched

### ISSUE THREAD

**Issue by sirenkovladd** [vanjs-org/van#228]
If a context is switched faster than a second (https://github.com/vanjs-org/van/blob/1.2.7/src/van.js#L5C83-L5C94) after the last change in a block that after switching will not be in DOM
reactivity breaks (but continues to work derive)

Reproduce
https://jsfiddle.net/Sirenko/03tma69r/2/

**Comment by sirenkovladd** [comment]
It seems that the problem is in the implementation of GC as it thinks that this element in _bindings is no longer used

**Comment by kwameopareasiedu** [comment]
It worked when I changed line 21 from `() => counter.val` to `p(() => counter.val)`.

I incremented the counter, went to the about page and returned to the page with the counter.val showing

**Comment by sirenkovladd** [comment]
I tried, still not working

https://jsfiddle.net/Sirenko/03tma69r/6/

**Comment by Tao-VanJS** [comment]
See https://vanjs.org/advanced#avoid-your-bindings-to-be-gc-ed-unexpectedly about the rules that have to be followed to avoid GC issues.

**Comment by sirenkovladd** [comment]
Made my component initialize the state once and return a function that will build DOM from the state and it's working

if anyone is interested, here is the result
https://jsfiddle.net/Sirenko/03tma69r/17/
