### ISSUE TITLE
It doesn't work. Did I do something wrong?

### ISSUE THREAD

**Issue by iuroc** [vanjs-org/van#232]
I put the State object created by van.state into a unified storage object, but when I use it, it doesn't work. Did I do something wrong?
![1704896313954](https://github.com/vanjs-org/van/assets/61752998/fa04ec35-cf9d-48bc-b916-d6751e85d776)
![1704896313961](https://github.com/vanjs-org/van/assets/61752998/071b391d-5d6b-490d-80db-17d93b8711ea)
![1704896313970](https://github.com/vanjs-org/van/assets/61752998/25121bdc-e770-4b6f-a496-329b9b183bbc)
![image](https://github.com/vanjs-org/van/assets/61752998/3d66758c-cd00-4b56-b5fb-1b9e13e0356a)

**Comment by iuroc** [comment]
这个是正常的，关闭了模态框的fade：

https://github.com/vanjs-org/van/assets/61752998/491e7e65-a530-4295-9bb5-e60d86c86623

下面是加上 fade：


![image](https://github.com/vanjs-org/van/assets/61752998/ff3dac45-52af-492c-aab5-a5861a0b89c9)

发现失效了：


https://github.com/vanjs-org/van/assets/61752998/2351e120-158e-4980-82b9-ec228388d354

**Comment by Tao-VanJS** [comment]
It seems as a Bootstrap Modal related issue. Do you have a link to your code that has the problem?

**Comment by iuroc** [comment]
@Tao-VanJS 
The following example encounters the same issue, seemingly related to elements not being loaded into the document tree or being affected by asynchronous operations:

```javascript
import van from 'vanjs-core'

const { button, div } = van.tags

const value = van.state('Hello World')

const app = div(
    div(value),
    button({
        onclick() {
            value.val = 'New Text'
        }
    }, 'Change Text')
)

setTimeout(() => {
    van.add(document.body, app)
}, 1000)
```

**Comment by iuroc** [comment]
This is similar to the issue with Bootstrap Modal. The `new Bootstrap.Modal(HTMLDivElement)` does not automatically add the element to the `document.body`. Instead, it is automatically added to the body when `Modal.show()` is executed, but only if the element doesn't exist in the body already. If the element is added to the body beforehand, it won't be automatically added again.

**Comment by iuroc** [comment]
```typescript
const modalEle = div({ class: 'modal' })
const modal = new Modal(modalEle)
console.log(document.querySelector('.modal') == null)  // true
```

**Comment by sirenkovladd** [comment]
@iuroc, this is related to the internal work of garbage collection, you can read more here
https://vanjs.org/advanced#avoid-your-bindings-to-be-gc-ed-unexpectedly

Here's a fixed example
```js
import van from 'vanjs-core'
const { button, div } = van.tags

const value = van.state('Hello World')

const app = () => div(
    div(value),
    button({
        onclick() {
            value.val = 'New Text'
        }
    }, 'Change Text')
)

setTimeout(() => {
    van.add(document.body, app())
}, 1000)
```

**Comment by iuroc** [comment]
Yes, I also noticed this. VanJS performs garbage collection after 1000ms of adding _bindings, as demonstrated in the video below. Therefore, in the future, I should be mindful that when creating DOM elements through van.tags.*, they should be added to the DOM tree synchronously during their construction process to prevent them from being collected. Thank you for your assistance!

https://github.com/vanjs-org/van/assets/61752998/53e19418-3ffd-4249-8d20-95b3e8431a9a

Here is the code example from the video, and I think I understand how to address it:

```ts
import van from 'vanjs-core'

const { button, div } = van.tags

const value = van.state('Hello World')

const app = div(
    div(value),
    button({
        onclick() {
            value.val = 'New Text'
        }
    }, 'Change Text')
)
console.log((<any>value)._bindings[0])
setInterval(() => {
    console.log((<any>value)._bindings[0])
}, 100)

van.add(document.body, button({
    class: 'btn', onclick() {
        van.add(document.body, app)
    }
}, 'Click Me'))
```

**Comment by iuroc** [comment]
> @Tao-VanJS The following example encounters the same issue, seemingly related to elements not being loaded into the document tree or being affected by asynchronous operations:
> 
> ```js
> import van from 'vanjs-core'
> 
> const { button, div } = van.tags
> 
> const value = van.state('Hello World')
> 
> const app = div(
>     div(value),
>     button({
>         onclick() {
>             value.val = 'New Text'
>         }
>     }, 'Change Text')
> )
> 
> setTimeout(() => {
>     van.add(document.body, app)
> }, 1000)
> ```

If I change it to `setTimeout(() => { van.add(document.body, app) }, 999)`, it will work fine. However, this is just for testing and learning purposes, and it's not recommended for real-world use.
