### ISSUE TITLE
vanX.list also looping empty values

### ISSUE THREAD

**Issue by mintong89** [vanjs-org/van#241]
Is there any ways to let vanX.list only looping non-deleted values?
For example if there are items deleted, the array value will show as:
```js
console.log(apples)
>> [[Target]]: Array(4)
>> ...
>> Symbol(): (4) [empty × 2, 'apple', 'apple', ...]
```

Then when I want to create elements using vanX.list with using index key, it will show like this:
```js
vanX.list(van.tags.ol, apples, (apple, deleter, index) => van.tags.li(index))
```
```html
<ol>
 <li>2</li>
 <li>3</li>
</ol>
```

But what I want is
```html
<ol>
 <li>0</li>
 <li>1</li>
</ol>
```

Is there any way to acheive it like adding ```filter(Boolean)``` on vanX.list?

**Comment by Tao-VanJS** [comment]
You can add this line:

```js
vanX.replace(apples, items => items)
```

This will eliminate all the holes in your reactive array `apples`.

**Comment by mintong89** [comment]
alright thanks for your solution!
