### ISSUE TITLE
Lifecycle event: mount and unmount

### ISSUE THREAD

**Issue by sirenkovladd** [vanjs-org/van#245]
For example for library [leaflet](https://leafletjs.com/) I need to initialize the map after mounting to dom, because this function calculates the block size from the actual size on the page
also if i leave the page a good practice is to unmount the map, this removes the listeners

Correct example on vue
https://jsfiddle.net/Sirenko/6oLkfj49/59/

example with errors on VanJs
https://jsfiddle.net/Sirenko/uvpk4t0g/39/

**Comment by Tao-VanJS** [comment]
You can leverage `setTimeout` to achieve the effect.

I just modified your example to make it work:
https://jsfiddle.net/8xj47fga/1/

**Comment by Tao-VanJS** [comment]
Hi @creatormir,

Does #388 answer your question?

**Comment by 7sDream** [comment]
It seems the provided examples are about mount events. How can I set a hook for unmounting? I need to remove an event listener that is only required while the component is active.

**Comment by Tao-VanJS** [comment]
Van Element supports `dismount` as well: https://van-element.pages.dev/learn/lifecycle.html#dismount

**Comment by 7sDream** [comment]
But I do not want to use Web Components. It seem to add complexity for me. For example, the `van.tags["xxx-xxx-xxx"]` syntax isn't very easy to type, and the component name being a string (instead of a type-checked symbol) increases the likelihood of typos.

**Comment by Tao-VanJS** [comment]
> So there is no built-in way(even like the `setTimeout` hack) to get an unmount hook for now?

I don't think there is an easy way to do that.

**Comment by thednp** [comment]
I've created a small utility, play around:


```ts
import van from "vanjs-core";

/**
 * Returns a connected state based on
 * the `Node.isConnected` property.
 * @param target A target Element/HTMLElement
 * 
 * @example
 * const myDiv = van.tags.div({ class: "my-div" });
 * const connected = isConnected(myDiv)
 * van.derive(() => {
 *   if (connected.val) {
 *     // do something here, now you know for sure is connected
 *   }
 * }) 
 */
export const isConnected = (target: Element) => {
  const connectedState = van.state(false);
  van.derive(() => {
    setTimeout(() => {
      connectedState.val = target.isConnected;
    });
  });
  return connectedState;
}
```
