### ISSUE TITLE
Script children should not be escaped

### ISSUE THREAD

**Issue by eevleevs** [vanjs-org/van#283]
```js
van.html(van.tags.script('const a = () => 1'))
```

becomes

```html
<!DOCTYPE html><html><script>const a = () =&gt; 1</script></html>
```

and does not work

**Comment by Tao-VanJS** [comment]
Thanks @eevleevs for reporting the bug!

After testing, the problem only appears in the van-plate mode of Mini-Van. It doesn't appear in VanJS or mini-van mode of Mini-Van.

I will consider getting it fixed in the next release of Mini-Van.

**Comment by eevleevs** [comment]
Thank you, confirmed I was working on mini-van, sorry for forgetting to mention.

**Comment by Tao-VanJS** [comment]
This bug should be fixed in Mini-Van [`0.5.6`](https://github.com/vanjs-org/mini-van/releases/tag/0.5.6). Thanks again for reporting!

**Comment by Tao-VanJS** [comment]
@all-contributors please add @eevleevs for bug

**Comment by eevleevs** [comment]
Great, confirmed working. Thanks!
