### ISSUE TITLE
Can createDocumentFragment be used directly?

### ISSUE THREAD

**Issue by creatormir** [vanjs-org/van#287]
Can be used directly, no need to pass through VanJS proxy constructor?
```
let fragment =  document.createDocumentFragment()
    fragment.appendChild( div(input()) )
```

**Comment by Tao-VanJS** [comment]
What do you mean by "VanJS proxy constructor"?

The code you pasted seems to be valid VanJS code.

**Comment by creatormir** [comment]
I mean by "VanJS proxy constructor" a function that adds a proxy to an object.
> The code you pasted seems to be valid VanJS code.

Yes, that is right.

**Comment by creatormir** [comment]
In my large project I tried to use `createDocumentFragment`. I encountered the problem that the resulting DOM has no bindings with the reactive store.
```
let line = document.createDocumentFragment(); 
line.appendChild(el1); // el1 = extern func: return div(....
line.appendChild(el2); // el2 = extern func: return div(....
return line; 
```
This breaks the bindings to the reactive store and as a result `van.derive` does not work in the extern func of creating the DOM.
So instead of `return line;` I use an extra div  `return div(el1, el2);`

Unfortunately, I have not yet been able to make a short example to repeat the error. Sorry.

**Comment by creatormir** [comment]
I managed to write some code to test it. It has to do with `vanX.list`. If in vanX.list return `createDocumentFragment` then the bindings break.
```
    let state = vanX.reactive({test: [{id:0, name:'MSB'}, {id:1, name:'LSB'}]});
    let elFn1 = (obj, key) => {
        let el1 = div({view:()=>obj[key]}, 'click' );
        van.derive(()=>{
            el1.innerText = obj[key]+'(click)';
            console.log(obj[key]);
        });
        el1.onclick = evt=>{
            obj[key] += 100;
        }
        return el1;
    }
    let list = vanX.list(div, state.test, (objItem, deleter, key) =>{
        objItem = objItem.val;
        let el1 = div( {}, 'start line: ');
        let el2 = div( span('new '+objItem.name), elFn1(objItem, 'id') );
        let line = document.createDocumentFragment(); 
        line.appendChild(el1)
        line.appendChild(el2)
        // return div(div(el1), div(el2)); // it works
        return line; // it doesn't work
    });
    return list;
```

**Comment by Tao-VanJS** [comment]
`DocumentFragment` cannot be treated as a DOM node for state binding. This is because in the DOM implementation, it's not represented as a standalone node, rather its children are just fused into its parent element.
