### ISSUE TITLE
HTML Character Entity for "&nbsp;" not correctly loading rendering when using span() tag.

### ISSUE THREAD

**Issue by frumsy** [vanjs-org/van#339]
I need to dynamically add spaces to the end of some words in my app. I was trying to do this:

```js
      van.add(wordSpan, span("&nbsp;"));
```
However it simply renders the text as: ''\&nbsp;" instead of " ".
![image](https://github.com/vanjs-org/van/assets/13265059/31909722-4b1f-4b46-9525-e8ae2b04041b)

I was able to fix this by doing the following:

```js
      const spaceSpan = document.createElement("span");
      spaceSpan.innerHTML = "&nbsp;";
      van.add(wordSpan, spaceSpan);
``` 

However, I expected this to work with the default span() tag.

**Comment by Tao-VanJS** [comment]
Hi @frumsy,

This is intended behavior. VanJS doesn't process HTML escape sequence while constructing the DOM tree. To construct DOM nodes with `&nbsp;`, you can consider specifying unicode character in the string, such as `span("\u00A0")` (`\u00A0` is the unicode character for `&nbsp;`).

**Comment by frumsy** [comment]
@Tao-VanJS I see. Unicode character works nice and looks a lot cleaner. Thank you! closing the issue
