### ISSUE TITLE
Raw form of reactive arrays do not support `length` or iteration

### ISSUE THREAD

**Issue by jroush-ipg** [vanjs-org/van#356]
The `raw` form of a reactive array will throw an exception when attempting to read its `length` or iterate over it.  

[The docs](https://vanjs.org/x#reactive-object) state that reactive objects cannot contain `State` values, and presumably they cannot contain DOM nodes either.  I did not see any caveats about arrays.

Minimal code to reproduce:
```javascript
const raw_val = raw(reactive( [1,2,3] ));
raw_val[0]; // OK
raw_val.length; // TypeError: obj is undefined
for (const x of raw_val) {} // TypeError: obj is undefined
raw_val.map(x => x+1); // TypeError: obj is undefined
raw_val.forEach(_ => {}); // TypeError: obj is undefined
```

**Comment by Tao-VanJS** [comment]
Hi @jroush-ipg,

[VanX `0.6.1`](https://github.com/vanjs-org/van/discussions/311#discussioncomment-10467986) should have fixed this bug. Let me know if things are working on your end.

**Comment by Tao-VanJS** [comment]
@all-contributors please add @jroush-ipg for bug

**Comment by jroush-ipg** [comment]
@Tao-VanJS VanX 0.6.1 does indeed fix the bug. That was an amazingly fast response time - thank you!
