### ISSUE TITLE
VanUI Toggle does not respond to first click when on is true

### ISSUE THREAD

**Issue by eevleevs** [vanjs-org/van#366]
See https://codesandbox.io/p/devbox/musing-merkle-h6hcgx?file=%2Fsrc%2Fmain.ts

**Comment by Tao-VanJS** [comment]
Thanks @eevleevs for reporting the bug. It was fixed in VanUI 0.10.1. See: https://codesandbox.io/p/sandbox/github/vanjs-org/van/tree/main/components/examples/toggle?file=%2Fsrc%2Fmain.ts%3A1%2C1.

**Comment by Tao-VanJS** [comment]
@all-contributors add @eevleevs for bug

**Comment by eevleevs** [comment]
Thanks for the quick fix!
