### ISSUE TITLE
Possibly faulty test case

### ISSUE THREAD

**Issue by bleistivt** [vanjs-org/van#384]
A few test cases use `Array.every` with `assertBetween`:

https://github.com/vanjs-org/van/blob/ac8a4ad8d22a45b910873c0f2ddfcafa6ffc35be/test/van.test.ts#L2121

This will only ever check the first element, since `Array.every` short circuits on the first faulty value and `assertBetween` throws or returns void. So only the first states bindings (`cond`) are checked.

When checking all binding, the ranges would have to start at 0, since a, b, c  or d could have 0 bindings depending on the last cond value.

**Comment by Tao-VanJS** [comment]
Thanks @bleistivt for the catch! I fixed the faulty tests in https://github.com/vanjs-org/van/commit/fe7d21a2449a33fafde80e31c1c018f1258400df.
