### ISSUE TITLE
RawVal prevents UI from reacting edge case

### ISSUE THREAD

**Issue by ericraider33** [vanjs-org/van#387]
Using the latest version of van (1.5.2) and the code sample below, please help me understand what the expected behavior should be.

```
import van from "/scripts/lib/van.js"
const {button, div, ul, li} = van.tags

let num = van.state(1);
num.rawVal = 2;

van.add(document.body,
    div(
        button({onclick: () => num.val = 1}, "Set to 1"),
        button({onclick: () => num.val = 2}, "Set to 2"),
        button({onclick: () => num.val = 3}, "Set to 3"),
    ),
    div(
        div("Value:"),
        div(() => num.val)
    )
);
```

When page is shown, the "Value" is shown as 2, which was set via the `rawVal` call.  With the initial state of the page, clicking the #1 button does NOT update the UI. It changes the state variable, but the UI dosen't react. 

I would think that the change using the `rawVal` should stop he UI from reacting to only that change, BUT any follow-up changes via the `val` property should cause he UI to react.

Thoughts?

**Comment by sirenkovladd** [comment]
Looking at this line, you also need to update `_oldVal` in this case
https://github.com/vanjs-org/van/blob/main/src/van.js#L123

better if you just update with `.val =`

**Comment by Tao-VanJS** [comment]
`rawVal` intends to be a readonly property. Setting the property `rawVal` leads to undefined behavior. In your example, simply having `let num = van.state(2);` will just work.

**Comment by ericraider33** [comment]
For completeness, I'll show the full example. I was using `rawVal` to prevent triggering a derived listening (`doSomething` function). But once a button is clicked, I want the `doSomething` method to react.

```
import van from "/scripts/lib/van.js"
const {button, div, ul, li} = van.tags

let num = van.state(1);
van.derive(() => doSomething(num.val));

// Don't trigger `doSomething` 
num.rawVal = loadInitialStateFromServer();

van.add(document.body,
    div(
        button({onclick: () => num.val = 1}, "Set to 1"),
        button({onclick: () => num.val = 2}, "Set to 2"),
        button({onclick: () => num.val = 3}, "Set to 3"),
    ),
    div(
        div("Value:"),
        div(() => num.val)
    )
);

function doSomething(newValue)
{
    console.log(newValue);
}

function loadInitialStateFromServer()
{
    return 2;
}
```

**Comment by ericraider33** [comment]
And, I'll add, I know there are a ton of ways that I can change my code to handle this specific scenario, I guess what I'm specifically looking for is what is **proper** way to update a van-state without triggering UI updates and/or derived states.

Unfortunately, simple tricks like the following don't work, because Van reacts in the BG.
```
let ignore = true;
num.val = 1;
ignore = false;

function doSomething()
{
    if (ignore) return;
// do something
}
````

**Comment by Tao-VanJS** [comment]
> I guess what I'm specifically looking for is what is proper way to update a van-state without triggering UI updates and/or derived states.

Unfortunately this is not possible. When we bind a UI element or a derived state with underlying dependency states, we have the expectation that the UI element or the derived state is in sync with the underlying dependencies. Allowing updating a state without triggering downstream updates will break this expectation, which could lead to tricky bugs.

**Comment by Tao-VanJS** [comment]
In your example, you can just swap `van.derive(...)` and `loadInitialStateFromServer` and things will just work as you expected.

**Comment by sirenkovladd** [comment]
this is possible for specific versions of the van
here is example
https://jsfiddle.net/pq3fxytk/

but it can be broken at any time
(for 1.5.2.min.js  -> `oldValKey`=`h`)

**Comment by ericraider33** [comment]
Thanks for your replies, which make perfect since. I've got what I need to move forward.
