### ISSUE TITLE
How to call a function after an element is rendered(mounted event)?

### ISSUE THREAD

**Issue by creatormir** [vanjs-org/van#388]
I'm interested in an analogue of `mounted` in `vue.` Any ideas on how to implement this?

**Comment by sirenkovladd** [comment]
https://github.com/vanjs-org/van/issues/245
or
https://github.com/vanjs-org/van/discussions/376

**Comment by creatormir** [comment]
> #245
> or
> #376

I want to avoid using `setTimeout`
And how to track the `mounted event` in the second example (376)?

**Comment by creatormir** [comment]
Thanks!
`vanjs-element / vanE` This is something new🤔, I didn't find documentation for vanE

**Comment by sirenkovladd** [comment]
`van-element` it's just wrapper for [customElements.define](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define) ([code](https://github.com/Atmos4/van-element/blob/main/src/van-element.js))

**Comment by creatormir** [comment]
Exactly, I found [the documentation](https://van-element.pages.dev/intro/get-started.html)
