### ISSUE TITLE
list attribute for input

### ISSUE THREAD

**Issue by ndrean** [vanjs-org/van#47]
The ìnput` tag does not support the "list" attribute whilst it is needed for the [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist). 

```
Cannot set property list of #<HTMLInputElement> which has only a getter
```

see the example: <https://codesandbox.io/s/stupefied-david-7pzk7e?file=/src/index.js>

**Comment by ndrean** [comment]
Idem for the `form` attribute on the `button` tag: <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attributes>

**Comment by ndrean** [comment]
an example in vanilla where you can setAttribute "list" on an input and "form" on a button to link to the form

<https://codesandbox.io/s/elegant-snowflake-ejhz9d?file=/src/index.js>

**Comment by Tao-VanJS** [comment]
Thanks for all the bug reports! I'm hoping to get it addressed by the end of this week.
