### ISSUE TITLE
[Feature Request] add https://react.dev/reference/react/Fragment

### ISSUE THREAD

**Issue by wuyudi** [vanjs-org/van#51]
but how to name it is a problem. It shouldn't conflict with future HTML tags.

https://react.dev/reference/react/Fragment

**Comment by Tao-VanJS** [comment]
For most of the cases, simply returning an array of elements would just work, e.g.:

```js
const Blog = () => [
  Post({title: "An update", body: "It's been a while since I posted..."}),
  Post({title: "My new blog", body: "I am starting a new blog!"}),
]

const Post = ({title, body}) => [
  PostTitle({title}),
  PostBody({body}),
]

const PostTitle = ({title}) => h1(title)
const PostBody = ({body}) => article(p(body))
```

[Try on jsfiddle](https://jsfiddle.net/j2rd70of/)

For elements created with `van.bind`, you can wrap them into a pass-through container (i.e.: `span` for inline elements and `div` for block elements).
