### ISSUE TITLE
bind() not picking up changes even when `onnew` does

### ISSUE THREAD

**Issue by benallfree** [vanjs-org/van#65]
I have a pattern like this:

```ts
const myStoreFactory = ()=> {
   const foo = state(false)
}

const myStore = myStoreFactory()

const myComponent = ()=>{
   const { foo } = myStore
   foo.onnew(console.log) // This works
   return bind(foo, foo=>{
      return div(foo ? `foo` : `no foo`)
   })
}

const toggle = ()=>{
   foo.val = !foo.val
   setTimeout(toggle, 1000)
}

```

In some cases, and I can't figure out exactly why, `bind()` is not picking up the changes even when `onnew` will fire. Any ideas?

**Comment by Tao-VanJS** [comment]
For DOM nodes that are bound to states, they need to connect to the `document` object (`isConnected` property needs to be `true`) before state changes are made. Otherwise the DOM nodes are considered obsolete and the bindings will be GC-ed. https://vanjs.org/advanced#gc has a detailed explanation of this mechanism.

You can reply to this thread if you have more questions, or close this bug if everything is good.

**Comment by benallfree** [comment]
Thank you. 

> Please complete the construction of the DOM tree and connect the newly constructed DOM tree to the [document](https://developer.mozilla.org/en-US/docs/Web/API/Window/document) object before making any state changes.

Could you explain more? In my case, the issue was async execution where the component was being rendered with a correct initial state, but the state update happening in the `then()` was not working for `bind` even though `onnew` was responding to it. It seems that my DOM tree was constructed and connected, but modifying the state in an async callback failed.

**Comment by Tao-VanJS** [comment]
Could you show me the code that is not working?

**Comment by Tao-VanJS** [comment]
> This works every time, is there any problem with doing this? It seems to eliminate the need to reason through race conditions.
> 
> ```ts
> const wrapState = (originalStateVar: State<any>) => {
>   const wrapped = state(originalStateVar.val)
>   originalStateVar.onnew((v) => {
>     wrapped.val = v
>   })
>   return wrapped
> }
> 
> return div(bind(wrapState(myStateVar)...))
> ```

The problem is GC, every time `wrapState`` is called, it creates an event listener for `originalStateVar` that will never be cleaned up. Thus there will be problems if `wrapState` is called many times.

**Comment by benallfree** [comment]
I'll see if I can distill it down to a concise example.

I did notice that wrapping the renders in `setTimeout` also fixed the issue. Could this be a clue? Is there something about waiting until the next tick for the state to settle?

In the mean time, can you please explain more about this statement:

> Please complete the construction of the DOM tree and connect the newly constructed DOM tree to the [document](https://developer.mozilla.org/en-US/docs/Web/API/Window/document) object before making any state changes.

How is it possible to construct and connect the DOM tree to the document when the tree depends upon state variables? That seems to be a contradiction, can you say more please?

**Comment by benallfree** [comment]
Ok I figured out the issue. I was indeed passing the **result** of a render function and then connecting it to the document tree later. The debug version of Van didn't complain about this, I wonder if there is a more robust check? 

Basically, any reference to a state binding where `isConnected===false` should complain. I see the debug check, but it wasn't complaining.

**Comment by benallfree** [comment]
This has been a very interesting issue, I'm also finding out that the order of state changes can produce `bind` warnings, where a bind update scheduled with `setTimeout` will attempt an operation in the next tick on a component that was unmounted from the document in the previous tick. 

This little helper comes in handy:

```ts
export const nextTick = () => new Promise((resolve) => setTimeout(resolve))
```
That way, I can `await nextTick()` to make sure components are fully unmounted and GC'd before making changes to state variables that might cause that `setTimeout` state update to be scheduled.

**Comment by Tao-VanJS** [comment]
Basically, the key is, before doing:

```js
s.val = ...
```

make sure all DOM nodes depend on the state `s` are connected to the `document` tree.

**Comment by Tao-VanJS** [comment]
Another rule you can follow is: whenever you bind a DOM node to states, always connect the DOM node to `document` within the same synchronous execution block (no `await` in between).

**Comment by benallfree** [comment]
This can be closed now. It took some learning, but now I understand how to architect things properly for Van.
