### ISSUE TITLE
Suggestion - readonly state proxy

### ISSUE THREAD

**Issue by benallfree** [vanjs-org/van#66]
This is more a dx issue, but I see a pattern frequently where I'd like to be able to `bind` to a state var, but prevent accidental writes to it because writes should be handled by a helper that adjusts multiple state variables or performs other side effects. It would be nice to have something like `State.readonly()` that returned a wrapped version where `get stateVar.val` worked but `set stateVar.val` threw an exception.

It might look something like this:

```js
  "readonly"() {
    let _this=this
    return { 
      ..._this,
      set "val"(v) { throw new Error(`State is read-only`) },
    }
  }
```

```ts
export type State<T> = {
  val: T
  onnew(l: (val: T, oldVal: T) => void): void
  readonly(): State<T> & { readonly val:T}
}
```

Or, if you don't want to actually add that to the code, I can basically get what I need from TS type checking

```ts
export type ReadOnlyState<T> = Omit<State<T>, 'val'> & { readonly val: T }
export const toReadOnlyState = <T>(state: State<T>) => state as ReadOnlyState<T>
```

**Comment by Tao-VanJS** [comment]
I think [`StateView<T>`](https://github.com/vanjs-org/van/blob/main/src/van.d.ts#L8) is exactly the TypeScript type that you're looking for.

**Comment by Tao-VanJS** [comment]
Also, I think you can have a `readonly(s: State<T>)` helper function by your own.
