### ISSUE TITLE
Real World Template

### ISSUE THREAD

**Issue by cayter** [vanjs-org/van#7]
Is there a real world template that provides the below?

- demo how SSR works
- demo how interactivity is achieved with SSR, i.e. does this support hydration?
- demo how components can be structured in individual files and imported to pages/routes

Thanks!

**Comment by Tao-VanJS** [comment]
Hi,

Thanks for reaching out! These are great questions and I am happy to answer. I am wondering whether you can re-post the questions into our [Discussions](https://github.com/vanjs-org/van/discussions) page? This way your questions and my answers will be more discoverable to other VanJS users.

Thank you so much!
