### ISSUE TITLE
SSR and Hydration Support for VanJS

### ISSUE THREAD

**Issue by roman-koshchei** [vanjs-org/van#85]
Astro js support is a bit more complex one. But supporting [Vite](https://vitejs.dev) as bundle tool is really necessary nowadays.
I really like minimal frameworks like Van. But it's really hard to use them when you need SEO. Good SEO requires SSR, but SSR requires some kind of hydration.

**Comment by Tao-VanJS** [comment]
Hydration can be the next stage of the VanJS project. I'm looking into that. I am wondering whether you can share a little bit more information about the use cases that you're looking for? The more I can understand use cases, the more help I will get while designing the hydration mechanism.

**Comment by roman-koshchei** [comment]
I saw video from Awesome about Vanjs. And some other guys also prefer small and simple frameworks to works with. 

But if I have to build store I cannot use Vanjs. Because I need my products to be rendered without js and then using js to search. 

I think if somehow integrate with Astro it will solve most of it. Astro has docs about custom integration or you can contact them. The benefit is you get API routes, SSR, content with by default with Astro. And when you need js you just use Vanjs.

Or developing for Vite is also possible and maybe a little bit easier. Vite has plugging for ssr.

**Comment by roman-koshchei** [comment]
But building a Admin panel is current use case for Vanjs. I built small forms SaaS. So I need pages with good SEO for marketing, but also admin panel

**Comment by Tao-VanJS** [comment]
I see. Thanks @roman-koshchei for sharing your use cases!

We have a sister project - [Mini-Van](https://github.com/vanjs-org/mini-van) that supports SSR, and indeed the website https://vanjs.org/ is built entirely based on Mini-Van. However, we haven't achieved the ideal status in this regard. Specifically, there are 2 issues that need to be addressed better:
1. How to share re-usable components between server and client side? Right now we can implement server-side and client-side components respectively, but this will result in some duplication.
2. How to enable hydration? Right now hydration can be achieved with some code snippet, but it would be nice to encapsulate it into a single VanJS API.

So the next stage for VanJS will be offering some solution for the 2 issues above. With that solution:
- You can define shared components between server and client side.
- You can hydrate DOM nodes after a page is loaded, to add reactivity to your UI.

We don't want to tie VanJS with a specific framework, either Astro or Vite. But with the solution in place, you can easily do server-side rendering with any JavaScript runtime (Node.js, Deno, etc), and do client-side rendering with browsers. I think it will easy to integration with other frameworks like Vite, or you can work in an environment without any frameworks at all (I think we will probably share some examples that are not based on any framework).

I hope I can get a chance to work on this in a couple of weeks.

**Comment by jaymanmdev** [comment]
Hey there!

I just started using Van (I originally had a look at it pre-1.0).

I have created a basic, work-in-progress, integration/renderer for AstroJS with VanJS which does very mild hydration (just replaces the elements directly), but it works with SSR. It is very, very, very simple at the moment so it can definitely be expanded on in the future (and the API isn't optimal more than likely). I only started playing around with it tonight.

It is definitely possible to integrate Van into the full-stack story.

**Comment by Tao-VanJS** [comment]
Thanks @jaymanmdev for sharing your experience! I am working on some adjustments to VanJS (mostly on Mini-Van) so that the fullstack solution can be more seamless. Currently I have a sample app running. I'm planning to write a walkthrough about it soon. Stay tuned!

**Comment by jaymanmdev** [comment]
> Thanks @jaymanmdev for sharing your experience! I am working on some adjustments to VanJS (mostly on Mini-Van) so that the fullstack solution can be more seamless. Currently I have a sample app running. I'm planning to write a walkthrough about it soon. Stay tuned!

That's very exciting! Definitely keep me in the loop Tao!

It has been a pain - I wrote a helper function to use either vanjs-core or mini-van-plate based on the environment (client/server) you are in, as using vanjs-core throws an error on the server. It seems like it uses the document object immediately upon importing. That was definitely one issue that I had with my implementation, however I managed to write a solution that worked properly in both ends. It is great to hear that you are working on a more seamless hydration option for VanJS as right now I am just replace the entire content of the DOM node with the same VanJS element when it is "hydrated" on the client. It isn't the most ideal solution but it works hahaha

**Comment by Tao-VanJS** [comment]
@roman-koshchei, @jaymanmdev

With the VanJS [`1.2.0` release](https://github.com/vanjs-org/van/discussions/114), hydration supported is officially added.

**Comment by btakita** [comment]
> I have created a basic, work-in-progress, integration/renderer for AstroJS with VanJS which does very mild hydration (just replaces the elements directly), but it works with SSR. It is very, very, very simple at the moment so it can definitely be expanded on in the future (and the API isn't optimal more than likely). I only started playing around with it tonight.

@jaymanmdev Did you release your VanJS + AstroJS integration library?
